export const AUTH_USER_SUCCESS = "AUTH_USER_SUCCESS";
export const AUTH_USER_ERROR = "AUTH_USER_ERROR";
// load team members for authentication/permission purposes
export const AUTH_LOAD_TEAM_MEMBERS = "AUTH_LOAD_TEAM_MEMBERS";
export const AUTH_LOAD_TEAM_MEMBERS_PENDING = "AUTH_LOAD_TEAM_MEMBERS_PENDING";
export const AUTH_LOAD_TEAM_MEMBERS_SUCCESS = "AUTH_LOAD_TEAM_MEMBERS_SUCCESS";
export const AUTH_LOAD_TEAM_MEMBERS_ERROR = "AUTH_LOAD_TEAM_MEMBERS_ERROR";
export const AUTH_CLEAR_TEAM_MEMBERS = "AUTH_CLEAR_TEAM_MEMBERS";
export const AUTH_LOAD_V5_USER_PROFILE = "AUTH_LOAD_V5_USER_PROFILE";
export const AUTH_LOAD_V5_USER_PROFILE_PENDING =
  "AUTH_LOAD_V5_USER_PROFILE_PENDING";
export const AUTH_LOAD_V5_USER_PROFILE_SUCCESS =
  "AUTH_LOAD_V5_USER_PROFILE_SUCCESS";
export const AUTH_LOAD_V5_USER_PROFILE_ERROR =
  "AUTH_LOAD_V5_USER_PROFILE_ERROR";
